services:
  backend:
    build:
      context: .
      dockerfile: Adis.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - path: ./environment/default.env
        required: true
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    build:
      context: ./adis.client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    env_file:
      - path: ./environment/mysql.env
        required: true
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: