services:
  backend:
    image: ghcr.io/pluhenciya/adis-backend:latest
    build:
      context: .
      dockerfile: Adis.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - "./environment/default.env"
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
    networks:
      - app-network
      
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - app-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    image: ghcr.io/pluhenciya/adis-frontend:latest
    build:
      context: ./adis.client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - "./environment/frontend.env"
    depends_on:
      - backend
    networks:
      - app-network

  mysql:
    image: mysql:8.4
    env_file:
      - "./environment/mysql.env"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

networks:
  app-network:
    external: false
    driver: bridge

volumes:
  mysql-data:
  ollama-data: