services:
  backend:
    image: ghcr.io/pluhenciya/adis-backend:latest
    build:
      context: .
      dockerfile: Adis.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - "./environment/default.env"
    volumes:
      - documents-data:/app/documents
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
    networks:
      - app-network
      
  ollama:
    image: ollama/ollama:latest
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "
      # Запускаем сервер в фоне
      ollama serve &
      
      # Ждем инициализации сервера
      until wget -q --spider http://localhost:11434; do
        sleep 1
      done
      
      # Загружаем модели
      ollama pull nomic-embed-text
      ollama pull qwen3:1.7b
      
      # Оставляем сервер работать в основном процессе
      wait
      "
    environment:
      - OLLAMA_CPU_OVERRIDE=1
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_LOADED_MODELS=1
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:11434"]
      interval: 30s
      timeout: 30s
      retries: 10

  frontend:
    image: ghcr.io/pluhenciya/adis-frontend:latest
    build:
      context: ./adis.client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - "./environment/frontend.env"
    depends_on:
      - backend
    networks:
      - app-network

  mysql:
    image: mysql:8.4
    env_file:
      - "./environment/mysql.env"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

networks:
  app-network:
    external: false
    driver: bridge

volumes:
  mysql-data:
  ollama-data:
  documents-data: