services:
  backend:
    container_name: backend
    image: ${BACKEND_IMAGE}:${IMAGE_TAG}
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;user=${MYSQL_USER};password=${MYSQL_PASSWORD};database=${MYSQL_DATABASE}

  frontend:
    container_name: frontend
    image: ${FRONTEND_IMAGE}:${IMAGE_TAG}
    environment:
      - NODE_ENV=test

  mysql:
    container_name: mysql
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}