// <auto-generated />
using System;
using Adis.Dal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Adis.Dal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250424104237_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Adis.Dm.Project", b =>
                {
                    b.Property<int>("IdProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_product");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProduct"));

                    b.Property<decimal>("Budget")
                        .HasColumnType("DECIMAL(15,2)")
                        .HasColumnName("budget");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('draft', 'inProgress', 'completed', 'overdue')")
                        .HasColumnName("status");

                    b.HasKey("IdProduct")
                        .HasName("PRIMARY");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_projects_status");

                    b.HasIndex("StartDate", "EndDate")
                        .HasDatabaseName("ix_projects_dates");

                    b.ToTable("projects", null, t =>
                        {
                            t.HasCheckConstraint("chk_projects_budget", "budget >= 0");

                            t.HasCheckConstraint("chk_projects_dates", "start_date <= end_date");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
